num1=int(input("ENTER THE FIRST NUMBER:\n"))
num2=int(input("ENTER THE SECOND NUMBER:\n"))
sum=num1+num2
sub=num1-num2
mul=num1*num2
div=num1/num2
mod=num1%num2
print("SUM OF",num1 ,"and",num2,"is= ",sum)
print("SUBTRACTION OF",num1 ,"and",num2,"is= ",sub)
print("MULTIPLICATION OF",num1 ,"and",num2,"is= ",mul)
print("DIVISION OF",num1 ,"and",num2,"is= ",div)
print("MODULUS OF",num1 ,"and",num2,"is= ",mod)