list=[1,2,3,4]
list.reverse()
print(list)
list.sort()
print(list)
list.insert(1,100)
print(list)
list.remove(3)
print(list)
list.pop(3)
print(list)
lst=["banana","chery","apple"]
list.extend(lst)
print(list)